# Restart the extraction service
Write-Host "Restarting the extraction service to apply cache-busting changes..."
Write-Host ""
Write-Host "Please follow these steps to see the changes:"
Write-Host ""
Write-Host "1. Restart your Django container with:"
Write-Host "   docker-compose down"
Write-Host "   docker-compose up -d"
Write-Host ""
Write-Host "2. After restarting, try these in your browser:"
Write-Host "   a. Clear browser cache completely (Ctrl+Shift+Delete in most browsers)"
Write-Host "   b. Perform a hard refresh (Ctrl+F5 or Cmd+Shift+R)"
Write-Host "   c. Open in an incognito/private window"
Write-Host "   d. Try a different browser"
Write-Host ""
Write-Host "Changes applied to prevent browser caching:"
Write-Host "- Added cache control headers to HTML templates"
Write-Host "- Added version parameters to CSS and JS resources"
Write-Host "- Added NoCacheMiddleware to Django settings"
Write-Host ""
Write-Host "If you still don't see the changes, please respond with the exact issue you're experiencing."
